# Site settings
title: Nasibeh Taraghi Delgarm
email: maysam@nasibeh.com
description: "Will be writing on education reform."
baseurl: "http://www.nasibeh.com/"
url: "http://www.nasibeh.com/"

# Build settings
markdown: kramdown
permalink: pretty
